version: "3.6"
services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  # API
  api:
    build:
      context: ./api
      target: deploy
    restart: always
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  mongodb-data:
